name: Build & Push Docker Image to GCP

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push to Google Container Registry
        run: |
          gcloud auth configure-docker
          gcloud builds submit --tag europe-west1-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-thibault/latest:latest quelpoke
